//
//  TextArrays.swift
//  kerrandsmith
//
//  Created by Sean Kelly on 17/05/2023.
//

import Foundation

let recoveryBlock: [String] = ["Kerr and Smith Cumnock have been dedicated to providing exceptional recovery and roadside assistance services for over 45 years. Our team of friendly and knowledgeable staff members is fully trained to handle all aspects of vehicle recovery and repair in a safe and responsible manner.", "We offer a comprehensive range of services, including both Light Recovery and Heavy Recovery options. Our fleet consists of six specialized vehicles designed to cater to different needs. For quick on-the-spot repairs, we have a Roadside Service vehicle equipped to handle kerbside repairs. In addition, we have a 7-ton Spec lift and two 14-ton crewcab slidebeds for efficient vehicle recovery. \n\nFor heavier vehicles weighing up to 26 tons, we have an 18-ton underlift available. Furthermore, we possess an Artic unit coupled to a 44-ton traveling axle trailer, ensuring we can handle even the most challenging recovery situations.We take pride in offering round-the-clock service, and our 24-hour recovery hotline is available for any emergencies or assistance you may require.", "We take pride in offering round-the-clock service, and our 24-hour recovery hotline is available for any emergencies or assistance you may require.", "Please feel free to contact us at 01290 428800 to speak with one of our team members and benefit from our expertise and reliable service."]

let servicesBlock: [String] = [
    "At Kerr & Smith, we specialize in keeping your Vauxhall in optimal condition. Our expert technicians offer maintenance, repairs, and parts replacements using genuine components. Located in Cumnock, our dealership is your go-to destination for top-notch Vauxhall care.\n\nWith our extensive knowledge and competitive prices, we provide regular servicing, MOTs, and service plans to ensure your vehicle performs at its best while safeguarding its resale value. Trust us to swiftly diagnose and fix any issues with your Vauxhall using genuine repair parts. Visit our website for more information and book an appointment today for a comprehensive service.",
    
    "We prioritize genuine parts for optimal performance and fit. We also stock a diverse range of aftermarket parts for various makes and models. With convenient delivery across Ayrshire, finding the right parts for your vehicle has never been easier.",
    
    "Experience excellence at our Approved Bodyshop Accident and Repair Centre! We provide top-quality repairs for all vehicle makes and models. Our skilled technicians specialize in restoring vehicles to their original condition after accidents. With advanced tools and genuine parts, your vehicle will receive the utmost care and attention it deserves. Trust us for exceptional quality and service.",
    
    "At our sales department, we pride ourselves on offering a diverse range of vehicles to cater to our customers' needs. Our car selection includes popular models from Vauxhall and SsangYong. From Vauxhall, you'll find reliable and stylish options such as the Vauxhall Astra, Vauxhall Corsa, and Vauxhall Insignia. These models are known for their excellent performance, cutting-edge features, and comfortable interiors.\n\nIn addition to the Vauxhall lineup, we also offer cars from SsangYong, a brand known for its ruggedness and versatility. Among the SsangYong models available, you can explore the SsangYong Korando, SsangYong Tivoli, and SsangYong Rexton. These vehicles boast powerful engines, advanced safety features, and spacious interiors, making them ideal choices for both urban driving and off-road adventures.\n\nIf you're in the market for nearly new cars, we have an extensive collection encompassing various makes and models. Our nearly new inventory includes popular choices from different manufacturers, ensuring that you have a wide range of options to choose from.\n\nFor customers seeking vans, we offer reliable and efficient models from Vauxhall. The Vauxhall Vivaro and Vauxhall Movano are among our top-selling van options. These vans are renowned for their practicality, spacious cargo areas, and advanced technology features, making them perfect for businesses and individuals alike.\n\nFurthermore, if you require trailers, we proudly provide a selection from Brian James Trailers. With their exceptional build quality and durability, Brian James Trailers are trusted for transporting various goods, from construction materials to recreational vehicles. Our trailer options include the Brian James A-Max, Brian James Cargo Connect, and Brian James Tiltbed models.\n\nVisit our sales department to explore our extensive range of vehicles, where our knowledgeable staff will be delighted to assist you in finding the perfect car, van, or trailer that meets your specific requirements.",
    
    "At Brian James Trailers, we not only sell trailers but also ensure excellent customer support throughout the ownership experience. We take pride in maintaining a comprehensive stock of most trailer parts, allowing us to promptly address any maintenance or repair needs. Our dedicated aftersales department consists of highly trained professionals who are well-versed in all aspects of servicing and repairs. You can rely on our expertise to provide top-notch assistance and keep your trailer in optimal condition for years to come."]

let aboutBlock: [String] = ["We take great pride in representing the Vauxhall name, providing motorists in the East Ayrshire region with all the latest new cars and vans from this prestigious marque. In fact, such is our dedication to delivering the best possible levels of service, we take added pride in being named a recipient of the Vauxhall Customer Excellence Award in both 2017 and 2019. We continue to strive to uphold these standards and go the extra mile to ensure we help find the automotive solution to suit you.",
                            
    "It’s part of our remit to ensure that all customers receive the care and attention they deserve when visiting our dealership. That’s why, whether you’re paying us a visit to purchase a new car, wish to browse our Approved Used selection at leisure, or are dropping your current vehicle in for a little TLC, you can expect to be greeted by a friendly face and a warm welcome.",
                            
    "Our modern showroom is the perfect environment to explore and learn more about the Vauxhall marque. Our sales and aftersales experts undergo extensive training and assessment to ensure that they’re able to always provide the required levels of service. In addition, they have many years’ experience working with us and a passion for all things Vauxhall, meaning you receive nothing but the very best advice and support.",
                            
    "Business motorists and those looking to take advantage of the Motability Scheme will also find that we’re able to offer the necessary support to help you. With experts located on-site to answer any questions you have and help secure the best deal, we will be happy to help you with any automotive need you should have."]
